project_name: go-release-please

builds:
  - id: cmd1
    main: ./cmd/cmd1
    binary: cmd1
    env:
      - CGO_ENABLED=0
      - VPREFIX=github.com/celest-io/go-release-please/pkg/util/build
    flags:
      - -tags=netgo
    ldflags:
      - -extldflags "-static"
      - -s
      - -w
      - -X {{ .Env.VPREFIX}}.Branch={{ .Branch }}
      - -X {{ .Env.VPREFIX}}.Version={{ .Tag }}
      - -X {{ .Env.VPREFIX}}.Revision={{ .ShortCommit }}
      - -X {{ .Env.VPREFIX}}.BuildUser={{ .Env.USER}}
      - -X {{ .Env.VPREFIX}}.BuildDate={{ .Timestamp }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

  - id: cmd2
    main: ./cmd/cmd2
    binary: cmd2
    env:
      - CGO_ENABLED=0
      - VPREFIX=github.com/celest-io/go-release-please/pkg/util/build
    flags:
      - -tags=netgo
    ldflags:
      - -extldflags "-static"
      - -s
      - -w
      - -X {{ .Env.VPREFIX}}.Branch={{ .Branch }}
      - -X {{ .Env.VPREFIX}}.Version={{ .Tag }}
      - -X {{ .Env.VPREFIX}}.Revision={{ .ShortCommit }}
      - -X {{ .Env.VPREFIX}}.BuildUser={{ .Env.USER}}
      - -X {{ .Env.VPREFIX}}.BuildDate={{ .Timestamp }}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"

archives:
  - id: cmd1
    builds:
      - cmd1
    name_template: "cmd1_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
  - id: cmd2
    builds:
      - cmd2
    name_template: "cmd2_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz

release:
  prerelease: "false"
  extra_files:
    - glob: config/release/*.yaml

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: config/release/*.yaml

snapshot:
  name_template: "{{ incpatch .Version }}-next"

source:
  rlcp: true
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source_code"

sboms:
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"
dockers:
  - id: cmd1
    ids:
      - cmd1
    dockerfile: cmd/cmd1/Dockerfile.gorelease
    image_templates:
      - "ghcr.io/celest-io/cmd1:latest"
      - "ghcr.io/celest-io/cmd1:{{ .Tag }}"
      - "ghcr.io/celest-io/cmd1:v{{ .Major }}"
      - "ghcr.io/celest-io/cmd1:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=cmd1"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
  - id: cmd2
    ids:
      - cmd2
    dockerfile: cmd/cmd2/Dockerfile.gorelease
    image_templates:
      - "ghcr.io/celest-io/cmd2:latest"
      - "ghcr.io/celest-io/cmd2:{{ .Tag }}"
      - "ghcr.io/celest-io/cmd2:v{{ .Major }}"
      - "ghcr.io/celest-io/cmd2:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=cmd2"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: all
    output: true

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: checksum
    output: true

changelog:
  skip: true
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
