name: build

on:
  push:
    branches:
      - feature/workflows
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.19.3

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/open-feature/flagd
      GOBIN: /home/runner/work/open-feature/flagd/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run test
        run: make test
